# Generated by Django 6.0.1 on 2026-01-28 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(unique=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=140)),
                ('text_template', models.TextField(help_text="Используй {var} плейсхолдеры. Например: 'Найди {a}+{b}'.")),
                ('generator_key', models.CharField(help_text="Ключ генератора из services/generators.py (например, 'type16_sum').", max_length=80)),
                ('difficulty', models.PositiveSmallIntegerField(default=1)),
                ('tags', models.CharField(blank=True, default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='EduOGE.exercisetype')),
            ],
            options={
                'ordering': ['exercise_type__code', 'difficulty', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.CharField(max_length=64)),
                ('task_vars', models.JSONField(default=dict)),
                ('correct_answer', models.CharField(max_length=200)),
                ('user_answer', models.CharField(blank=True, default='', max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('exercise_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduOGE.exercisetype')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EduOGE.tasktemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
